from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('doctor-dashboard/', views.doctor_dashboard, name='doctor_dashboard'),
    path('patient-dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path("", views.home, name="home"),
    path("create_appointment_slot/", views.create_appointment_slot, name="create_appointment_slot"),
    path("update_appointment_slot/<int:pk>/", views.update_appointment_slot, name="update_appointment_slot"),
    path("appointment_slot_list/", views.appointment_slot_list, name="appointment_slot_list"),
    path("delete_appointment_slot/<int:pk>/", views.delete_appointment_slot, name="delete_appointment_slot"),
    path("doctor_list/", views.doctor_list, name="doctor_list"),
    path("create_appointment/<int:doctor_id>/", views.create_appointment, name="create_appointment"),
    path("update_appointment/<int:pk>/", views.update_appointment, name="update_appointment"),
    path("appointment_list/<int:pk>/", views.appointment_list, name="appointment_list"),
    path("create_prescription/<int:appointment_id>", views.create_prescription, name="create_prescription"),
    path("update_prescription/<int:pk>/", views.update_prescription, name="update_prescription"),
    path("prescription_detail/<int:apoint_id>/", views.prescription_detail, name="prescription_detail"),
    path("upload_report/", views.upload_report, name="upload_report"),
    path("report_view/<int:patient_id>/", views.report_view, name="report_view"),
    path("edit_report/<int:report_id>/", views.edit_report, name="edit_report"),
    path("appointment_prescription_history/<int:pk>/", views.appointment_prescription_history, name="appointment_prescription_history"),
    path("create_review/<int:doctor_id>/", views.create_review, name="create_review"),
    path("show_review/<int:doctor_id>/", views.show_review, name="show_review"),
    path('payment/initiate/<int:appointment_id>/', views.initiate_payment, name='initiate_payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/failed/', views.payment_failed, name='payment_failed'),
    path('payment/canceled/', views.payment_canceled, name='payment_canceled'),
    path('payment/ipn/', views.payment_ipn, name='payment_ipn'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path("otp_view/<int:otp>/<str:email>/", views.otp_view, name="otp_view"),
    path("set_password/<str:email>/", views.set_password, name="set_password"),
    path("search_doctor/", views.search_doctor, name="search_doctor"),
    path("today_appointments/<int:doctor_id>/", views.today_appointments, name="today_appointments"),
    path("update_doctor_profile/<int:doctor_id>/", views.update_doctor_profile, name="update_doctor_profile"),
    path("update_password/", views.update_password, name="update_password"),
    path("doctor_profile/<int:user_id>/", views.doctor_profile, name="doctor_profile"),
    path("patient_profile/<int:user_id>/", views.patient_profile, name="patient_profile"),
    path("update_patient_profile/<int:user_id>/", views.update_patient_profile, name="update_patient_profile"),
    path("doctor_details/<int:doctor_id>/", views.doctor_details, name="doctor_details"),
    path('video_chat/<int:room_id>/', views.video_chat, name='video_chat'),
    path("doctor_category/<str:cat_name>/", views.doctor_category, name="doctor_category"), 
    path("appointment_details/<int:appoint_id>/", views.appointment_details, name="appointment_details"),
    path("about/", views.about, name="about"),
]


