# Generated by Django 5.1.5 on 2025-02-11 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentslot",
            name="decider1",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name="appointmentslot",
            name="decider2",
            field=models.TimeField(default=datetime.time(0, 10)),
        ),
    ]
