# Generated by Django 5.1.5 on 2025-02-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0002_alter_appointmentslot_decider1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="last_checkup",
            field=models.DateField(blank=True, null=True),
        ),
    ]
