# Generated by Django 5.1.5 on 2025-02-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0003_patient_last_checkup"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="experience",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
